#!/bin/bash 
eval "$(dircolors -b ~/.dir_colors)"
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;36m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;33m'
export PS1="\[\e[1;33m\][\[\e[1;35m\]\u\[\e[1;36m\]@\[\e[1;32m\]Laptop \[\e[1;38m\]\W\[\e[1;33m\]]\\$\[\e[0m\]"
#while sleep 1;do tput sc;tput cup 0 $(($(tput cols)-34));echo -e "\e[36m`date +%c`\e[36m";tput rc;done &

